# Autogenerated from /home/scratch.isaacw_gpu/Code/triton/test/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
from pathlib import Path
def path(p):
    if not p: return ''
    return str((Path(__file__).parent / p).resolve())


import sys

config.triton_obj_root = "/home/scratch.isaacw_gpu/Code/triton/python"
config.llvm_src_root = ""
config.llvm_obj_root = "/home/scratch.isaacw_gpu/download/llvm/install"
config.llvm_tools_dir = "/home/scratch.isaacw_gpu/download/llvm/install/bin"
config.llvm_lib_dir = "/home/scratch.isaacw_gpu/download/llvm/install/lib"
config.llvm_shlib_dir = ""
config.llvm_shlib_ext = ""
config.llvm_exe_ext = ""
config.lit_tools_dir = ""
config.mlir_binary_dir = ""
config.python_executable = "/home/scratch.isaacw_gpu/anaconda3/envs/conda_0/bin/python3.10"
config.enable_bindings_python = 0


import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work
lit_config.load_config(config, "/home/scratch.isaacw_gpu/Code/triton/test/lit.cfg.py")
