repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: debug-statements
  # We're in the process of converting from autopep8 + flake8 + isort to ruff on
  # a directory-by-directory basis.
  #
  # autopep8 doesn't actually split long lines, and ruff is faster.
  # ruff is basically the same as Black, but it's much faster.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff-format
        # Keep this in sync with the autopep8/isort/flake8 exclusions below.
        files: '^python/triton/runtime/.*'
        stages: [commit, push, manual]
      - id: ruff
        files: '^python/triton/runtime/.*'
        args: ["--fix", "--line-length", "120"]
        stages: [commit, push, manual]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: '^python/triton/runtime/.*'
        stages: [commit, push, manual]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
        exclude: '^python/triton/runtime/.*'
        args: ["-i"]
        stages: [commit, push, manual]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        # TODO: uncomment this to enable more flake8 plugins
        # additional_dependencies:
        #   - flake8-bugbear
        #   - flake8-comprehensions
        #   - flake8-docstrings
        #   - flake8-pyi
        #   - flake8-simplify
        stages: [commit, push, manual]
        exclude: |
          (?x)(
            ^python/triton/runtime/.*|
            ^test/|
            ^docs/conf.py$
          )
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
      - id: clang-format
        stages: [commit, push, manual]
        exclude: |
          (?x)(
            ^include/triton/external/|
            ^python/triton/third_party/
          )

exclude: |
  (?x)(
    ^include/triton/external/|
    ^python/triton/third_party/
  )
